### ISSUE TITLE
Issue E121: Undefined variable

### ISSUE THREAD

**Issue by Kwask94** [conornewton/vim-pandoc-markdown-preview#2]
Hello, thanks a lot for that plugin . I'm sure that it will make my workflow better 

however, there is small issue im facing when trying to start preview 
```
E121: Undefined variable: s:pdf_viewer
E116: Invalid arguments for function <SNR>80_OpenPdf
```
Can you help me fix that , I'm mac users and I just installed mupdf-tools
Thanks

**Comment by conornewton** [comment]
try putting the following in your vimrc:
```
let g:md_pdf_viewer="mupdf-x11"
```
Does this now open the preview?
I will need to make a change to my code so it updates.

**Comment by Kwask94** [comment]
I did , and it still give me the same message

**Comment by Kwask94** [comment]
Is installing Mupdf with `brew install mupdf-tools`
isn't enough ?

**Comment by conornewton** [comment]
It should be enough. Try instead:
```
let g:md_pdf_viewer="mupdf-gl"
```

**Comment by conornewton** [comment]
If not, you will need to find the command to open mupdf from terminal and set g:md_pdf_viewer equal to that.

**Comment by conornewton** [comment]
You could alternatively try evince:

```
brew install evince
```

**Comment by Kwask94** [comment]
Finaliy it worked, with evince it did, thanks very much for your help and for refering me to this awsome tool hjkl works great out the box. 

Again thank you for your help, the problem perhaps with mudpdf and macos machian. it might be worth mention in README file . 


Regards 😄
