### ISSUE TITLE
StartMdPreview causes problems with filenames containing whitespace

### ISSUE THREAD

**Issue by schwukas** [conornewton/vim-pandoc-markdown-preview#5]
When starting the preview of a markdown file that contains spaces these errors occur:

* For _zathura_ a separate window containing nothing will be opened for every whitespace separated word.
* For _mupdf_ no window will be opened at all.

I have not checked any other viewers but I'd suspect, the same would happen. I also haven't checked what causes this problem but wanted to just record it for now.

**Comment by conornewton** [comment]
Hey, I believe the following may be happening.

In vimscript % contains the current filename. So say we have a file "hello world.md" and consider the follwing line:

```
`execute "AsyncRun pandoc -t " .s:latex_class. " --pdf-engine=" .s:pdf_engine. " % -o %<.pdf && pkill -HUP mupdf"
```

It will become something like, 
```
pandoc -t latex --pdf-engine="pdflatex" hello world.md % -o hello world.pdf
```
So, hello and world.md are treated like two different arguments to pandoc. Hence it does not work.

I possible fix would be surrounding the file name with speech marks. So we get the following instead.

```
pandoc -t latex --pdf-engine="pdflatex" "hello world.md" % -o "hello world.pdf"
```

And hello world.md gets treated as a single argument.


I am not able to fix this until next month as i have exams and dont have access to a linux computer, but have a good if you think you can!

**Comment by schwukas** [comment]
#6 should do the trick.

**Comment by conornewton** [comment]
All working
