### ISSUE TITLE
Template Problem

### ISSUE THREAD

**Issue by MaxPalef** [conornewton/vim-pandoc-markdown-preview#8]
Hey, this vim plugin is amazing and works fine but I struglle to pass template argument to pandoc.

I tried :
```
let g:md_args = "--template mytemplate "
let g:md_args = "--template mytemplate.tex "
let g:md_args = "--template=mytemplate "
let g:md_args = "--template mytemplate.tex "
```
I tried some others arguments like --toc and --number-section and they worked fine
this template work I've already used it with pandoc to produce pdf

Btw i use zathura to preview and it works great with it !

Thank you for any help

**Comment by conornewton** [comment]
Hey, I will try to get this fixed as soon as possible! I have a couple ideas of what may be causing this issue.

I just want to confirm that its working fine if you run pandoc directly from the command line?

**Comment by MaxPalef** [comment]
no error by doing
``` $ pandoc  text.md -o text.pdf --toc --pdf-engine=xelatex --number-section --template=mytemplate.tex ```

**Comment by MaxPalef** [comment]
Ok i Fixed the problem by putting mytemplate.tex in /usr/share/pandoc/templates/

**Comment by conornewton** [comment]
Awesome, thanks for letting me know.
